name: hbcure
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.1+6
environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.1.0
  flutter_blue_plus: ^2.0.2
  elliptic: ^0.3.12
  convert: ^3.1.1
  ecdsa: ^0.1.2
  pointycastle: ^3.9.0
  yaml: ^3.1.1

  cupertino_icons: ^1.0.8
  # Localization packages required by gen_l10n
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/programs.json
    - assets/programs/Programs_decoded_full.json
    - doc/app_memory/40_ble_profiles.yaml
    - assets/program_names_DE_EN.csv
